In [122]:
import pandas as pd
import numpy as np
from math import factorial
import matplotlib.pyplot as plt
import networkx as nx
import seaborn as sns

In [123]:
credit = pd.read_excel('data/2 parte 2007 2.0.xlsx', index_col=0)
credit.info()
credit.head()


<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 122 entries, 2008-01-31 to 2007-08-06
Data columns (total 85 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   AAPL.O      122 non-null    float64
 1   HPQ.N       122 non-null    float64
 2   INTC.OQ     122 non-null    float64
 3   WMT         122 non-null    float64
 4   AMZN.O      122 non-null    float64
 5   CVS         122 non-null    float64
 6   BRKa        122 non-null    float64
 7   MCK         122 non-null    float64
 8   ABC         122 non-null    float64
 9   GOOGL.O     122 non-null    float64
 10  XOM         122 non-null    float64
 11  T           122 non-null    float64
 12  COST.O      122 non-null    float64
 13  CI          122 non-null    float64
 14  CAH         122 non-null    float64
 15  MSFT.O      122 non-null    float64
 16  WBA.O       122 non-null    float64
 17  KR          122 non-null    float64
 18  HD          122 non-null    float64
 19  JPM       

AAPL.O     HPQ.N    INTC.OQ        WMT     AMZN.O        CVS  \
2008-01-31  34.424844  7.428210  20.085673  16.488962  89.413119  21.092060   
2008-01-30  33.616105  7.397627  19.695383  15.975510  85.397008  19.525469   
2008-01-29  33.453339  7.370442  19.514517  15.926765  85.097814  19.682670   
2008-01-28  33.064229  7.441802  19.314612  15.829274  87.249712  19.238171   
2008-01-25  33.064229  7.431608  19.038553  15.627793  89.298044  19.276116   

                 BRKa        MCK        ABC    GOOGL.O  ...       E.TO  \
2008-01-31  15.166631  19.380108  18.506452  44.185313  ...  11.104350   
2008-01-30  15.501189  19.509638  18.705105  42.930147  ...  10.952236   
2008-01-29  15.579253  19.198150  18.959380  43.106324  ...  11.560694   
2008-01-28  15.434278  18.547417  17.997902  43.533848  ...  11.712808   
2008-01-25  15.512341  18.627602  17.866792  44.349746  ...  12.017037   

               UNFI.K     MDLZ.O  VIAB.O^L19     DLTR.O     AMGN.O        USB  \
2008-01-31  20.035928  12.738903   16.996273  13.676698  17.048137  13.296987   
2008-01-30  20.027572  12.817243   16.606007  12.509711  17.300620  13.155988   
2008-01-29  20.353428  13.139306   16.509537  13.085880  17.564081  13.285237   
2008-01-28  20.462046  13.248111   16.487612  12.944279  17.512853  13.171655   
2008-01-25  20.052638  12.960866   15.961412  12.597601  17.615310  12.909240   

               NFLX.O        LLY        TFC  
2008-01-31  26.665085  25.108589  12.676930  
2008-01-30  24.321950  25.089045  12.347932  
2008-01-29  24.555204  25.558091  12.442432  
2008-01-28  24.374962  25.113475  12.253433  
2008-01-25  23.081467  24.791006  11.903434  

[5 rows x 85 columns]

In [124]:
credito = credit.dropna()
credito

AAPL.O     HPQ.N    INTC.OQ        WMT      AMZN.O        CVS  \
2008-01-31  34.424844  7.428210  20.085673  16.488962   89.413119  21.092060   
2008-01-30  33.616105  7.397627  19.695383  15.975510   85.397008  19.525469   
2008-01-29  33.453339  7.370442  19.514517  15.926765   85.097814  19.682670   
2008-01-28  33.064229  7.441802  19.314612  15.829274   87.249712  19.238171   
2008-01-25  33.064229  7.431608  19.038553  15.627793   89.298044  19.276116   
...               ...       ...        ...        ...         ...        ...   
2007-08-10  34.939980  9.352636  24.634540  15.546175  103.059675  22.089813   
2007-08-09  35.328513  9.314996  24.572902  15.674404  102.136163  21.909606   
2007-08-08  37.458454  9.786491  25.353646  16.339175  107.194046  22.490917   
2007-08-07  42.552711  9.604232  24.788531  15.880247  109.068357  23.130333   
2007-08-06  42.622009  9.600270  24.788634  15.866749  108.875413  22.632646   

                 BRKa        MCK        ABC    GOOGL.O  ...        E.TO  \
2008-01-31  15.166631  19.380108  18.506452  44.185313  ...   11.104350   
2008-01-30  15.501189  19.509638  18.705105  42.930147  ...   10.952236   
2008-01-29  15.579253  19.198150  18.959380  43.106324  ...   11.560694   
2008-01-28  15.434278  18.547417  17.997902  43.533848  ...   11.712808   
2008-01-25  15.512341  18.627602  17.866792  44.349746  ...   12.017037   
...               ...        ...        ...        ...  ...         ...   
2007-08-10  14.267252  16.694516  18.134777  43.880923  ...  736.363636   
2007-08-09  14.343957  16.679623  17.334713  43.794139  ...  722.727273   
2007-08-08  14.445592  17.850175  17.959639  47.167056  ...  818.181818   
2007-08-07  14.406600  17.865068  18.910672  46.291498  ...  845.454545   
2007-08-06  14.318389  18.365457  19.708609  45.751452  ...  872.727273   

               UNFI.K     MDLZ.O  VIAB.O^L19     DLTR.O     AMGN.O        USB  \
2008-01-31  20.035928  12.738903   16.996273  13.676698  17.048137  13.296987   
2008-01-30  20.027572  12.817243   16.606007  12.509711  17.300620  13.155988   
2008-01-29  20.353428  13.139306   16.509537  13.085880  17.564081  13.285237   
2008-01-28  20.462046  13.248111   16.487612  12.944279  17.512853  13.171655   
2008-01-25  20.052638  12.960866   15.961412  12.597601  17.615310  12.909240   
...               ...        ...         ...        ...        ...        ...   
2007-08-10  25.658658  12.998726   18.452144  20.172311  14.374571  11.546881   
2007-08-09  27.205914  12.719662   17.565569  20.275547  14.635771  11.516048   
2007-08-08  27.197318  13.257568   18.452144  21.911837  20.021947  11.912539   
2007-08-07  26.724545  13.172636   18.362064  21.137567  19.787074  12.004765   
2007-08-06  25.280440  13.225213   18.414216  20.595578  19.933389  11.958652   

               NFLX.O        LLY        TFC  
2008-01-31  26.665085  25.108589  12.676930  
2008-01-30  24.321950  25.089045  12.347932  
2008-01-29  24.555204  25.558091  12.442432  
2008-01-28  24.374962  25.113475  12.253433  
2008-01-25  23.081467  24.791006  11.903434  
...               ...        ...        ...  
2007-08-10  19.986797  28.563148  13.921200  
2007-08-09  19.852732  28.907944  14.193887  
2007-08-08  20.076173  29.182782  14.636560  
2007-08-07  19.383506  28.243336  14.098269  
2007-08-06  18.947796  28.093425  14.123331  

[122 rows x 85 columns]

In [125]:
Firms=np.transpose(credito.values.tolist())
nfirms=credito.shape[1]
#nfirms=85

In [126]:
#vamos a construir la matriz de adyacenia 

A = np.zeros((nfirms,nfirms)) 
print(A)
for i in range (nfirms):
    for j in range (nfirms):
        ro=np.corrcoef(Firms[i],Firms[j])[0,1]
        d = (2*(1-ro))**0.5
        A[i,j]=d
        #al ser mat simétrica
        A[j,i] = d
A

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


array([[1.49011612e-08, 1.20661705e+00, 1.08734300e+00, ...,
        5.82720168e-01, 1.55469771e+00, 1.64582091e+00],
       [1.20661705e+00, 0.00000000e+00, 4.54360705e-01, ...,
        1.47854754e+00, 1.12355435e+00, 8.57405941e-01],
       [1.08734300e+00, 4.54360705e-01, 0.00000000e+00, ...,
        1.35869737e+00, 1.03122067e+00, 9.07336805e-01],
       ...,
       [5.82720168e-01, 1.47854754e+00, 1.35869737e+00, ...,
        1.49011612e-08, 1.68820348e+00, 1.73162456e+00],
       [1.55469771e+00, 1.12355435e+00, 1.03122067e+00, ...,
        1.68820348e+00, 0.00000000e+00, 8.18655337e-01],
       [1.64582091e+00, 8.57405941e-01, 9.07336805e-01, ...,
        1.73162456e+00, 8.18655337e-01, 1.49011612e-08]])

In [127]:
#matriz de adyacencia para una erdos-renyi
#num=70
#G = nx.erdos_renyi_graph(num, 0.3)
#A_er = nx.to_numpy_array(G)
#A_er # ojo, estabas machancando el anterior valor de A!!!

In [128]:
#definimos la medida de centralidad hasta tercer orden

# en la lista Re guardaremos cada valor de la medida de centralidad para cada e diferente de las 35 empresas

Re=[]
ones = np.ones(nfirms)
C=np.dot(A,A)
#D=A^4
D=np.dot(C,C)
for e in np.arange(0.01,1, 0.01):

    Rv=np.identity(nfirms)+A*e + (A*e)**2/factorial (2) + (A*e)**3/factorial (3)+(A*e)**4/factorial (4)

    #Rv=np.exp(e*A)
    Re.append(np.dot(Rv,ones))
  


In [129]:
# R es una matriz donde cada componente es la medida de centralidad para un riesgo diferente de una misma empresa
R=np.transpose(Re)
# Para hacer el ranking necesitamos solo Re ya que se hace comparando la centralidad de dif empresas para un mismo e
print(len(Re))
Re[5]

99


array([7.54815698, 6.67203618, 6.40818347, 8.75181349, 6.55798826,
       6.88377711, 7.69275579, 8.98152989, 8.41371527, 7.70855804,
       7.35486089, 7.02065465, 7.77828449, 6.94744792, 6.94867984,
       8.06881464, 7.19378509, 6.70950504, 7.01885337, 6.8321939 ,
       7.28556918, 8.21471341, 7.10795609, 7.00483358, 7.99187106,
       6.58538295, 6.64889177, 6.96484487, 6.48520255, 8.40448125,
       6.60294831, 6.29958498, 7.70946849, 6.45042809, 7.8308356 ,
       6.68345824, 6.4215585 , 7.39466332, 6.24002778, 9.15517733,
       7.78508823, 6.44931955, 9.11309358, 6.4250059 , 7.84411617,
       6.86784112, 6.46604432, 6.60729744, 7.19800538, 7.25347414,
       6.76915574, 8.04964433, 8.42752355, 6.60622236, 9.09846005,
       6.26347228, 7.29231112, 6.66816968, 6.78593412, 6.40293603,
       7.26927536, 6.93092297, 8.04380511, 8.96646567, 8.37667475,
       6.67182722, 8.35020407, 6.83176343, 6.3738455 , 6.26000454,
       7.87482386, 6.58566035, 6.51561671, 8.11500617, 6.42107

In [130]:
rank=[]
for i in range (len(Re)):
    test_list = Re[i]  

    res = sorted(range(len(test_list)), key = lambda sub: test_list[sub], reverse=True)
    # ahora que están ordenados de mayor a menor, ponemos el ranking de cada uno
    b = np.zeros(nfirms) 

    b[res] = np.arange(nfirms) # numpy permite estas cosas
    rank.append(b)

In [131]:
rankingboxplot=[]
for i in range (nfirms):
    rankingboxplot.append(ranking[i])
    
# Creating plot
plt.rcParams['font.size'] = 10
fig = plt.figure(figsize =(20, 10))
plt.boxplot(rankingboxplot)
plt.xlabel('Asset number') 
plt.ylabel('Ranking position') 
# show plot
plt.show()


IndexError: index 35 is out of bounds for axis 0 with size 35

In [ ]:
ranking[2]

In [ ]:
plt.figure(figsize=(25,20))
plt.boxplot(Re);
# se observa que 

In [ ]:
rankingstd=[]
for i in range (nfirms):
    rankingstd.append(ranking[i].std())
plt.hist(rankingstd)    
plt.ylabel('Counts') 
plt.xlabel('Standard deviations of Ranking position') 
plt.title('July-December of 2007')
print(sum(rankingstd)/len(rankingstd))